# Generated by Django 3.2.11 on 2022-01-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, default='', max_length=100)),
                ('product_inventory_instock', models.IntegerField()),
                ('product_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField()),
            ],
        ),
    ]
