# Generated by Django 3.2.11 on 2022-01-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_on',
        ),
    ]
