# Generated by Django 3.2.11 on 2022-01-18 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_auto_20220118_0922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False},
        ),
    ]
